name: pg-env
channels:
  - conda-forge
dependencies:
  - fenics-dolfinx=0.9.0
  - pyvista
  - pip
  - git
  - tqdm
  - scipy
  - trame-client
  - trame-vtk
  - trame-server
  - trame-vuetify
  - trame
  - ipywidgets
  - python-gmsh
  - scifem
  - pip:
      - git+https://github.com/METHODS-Group/ProximalGalerkin.git
variables:
  PYVISTA_TRAME_SERVER_PROXY_PREFIX: "/proxy/"
  PYVISTA_TRAME_SERVER_PROXY_ENABLED: "True"
  PYVISTA_OFF_SCREEN: false
  PYVISTA_JUPYTER_BACKEND: "html"
  LIBGL_ALWAYS_SOFTWARE: 1
