name: Test Firedrake examples

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:

  test-examples:
    runs-on: ${{ matrix.platform }}
    container: ${{ matrix.container }}
    env:
      DEB_PYTHON_INSTALL_LAYOUT: deb_system
    strategy:
      fail-fast: true
      matrix:
        platform: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        container: [
            "ghcr.io/methods-group/proximalgalerkin:v0.2.0-alpha"
          ]

    steps:
        - uses: actions/checkout@v4
        
        - name: Activate Firedrake virtual environment
          run: |
              . /firedrake-env/bin/activate
              echo PATH=$PATH >> $GITHUB_ENV

        - name: Run example 12
          working-directory: ./examples/12_monge_ampere
          run: |
            python3 monge_ampere_cg_cg_dg_firedrake.py
    