name: Test Firedrake examples

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:

  test-examples:
    runs-on: ubuntu-24.04
    container: 
        image: ghcr.io/methods-group/proximalgalerkin@sha256:360a5f7bc991157d146cccab764e5d24a0953ba8c838291c92e20fa3391c5eb6@sha256:dd41c6afdf8bf3ae54d719fa281c5db3412d69df27f13c374a20b6d35b8aa14b
        options: --user root

    steps:
        - uses: actions/checkout@v4
        
        - name: Activate Firedrake virtual environment
          run: |
              . /firedrake-env/bin/activate
              echo PATH=$PATH >> $GITHUB_ENV

        - name: Run example 12
          working-directory: ./examples/12_monge_ampere
          run: |
            source firedrake-mode
            python3 monge_ampere_cg_cg_dg_firedrake.py
    