name: Run Julia scripts

on:
    push:
      # The CI is executed on every push on to main
      branches:
        - main
    pull_request:
      # The CI is executed on every pull request to the main branch
      branches:
        - main

    schedule:
      # The CI is executed every day at 8am
      - cron: "0 8 * * *"
    workflow_dispatch:
    # The CI is executed manually
jobs:
  run-script:
    runs-on: ${{ matrix.platform }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: true
      matrix:
        platform: ["ubuntu-24.04", "ubuntu-24.04-arm"]
        container: [
          "ghcr.io/methods-group/proximalgalerkin:v0.2.0-alpha",
          "julia:latest"
          ]
    steps:
      - uses: actions/checkout@v4

      - name: Run Finite Difference
        working-directory: ./examples/01_obstacle_problem
        run: julia finite_difference.jl

      - name: Run Spectral method
        working-directory: ./examples/01_obstacle_problem
        run: julia spectral.jl

      - name: Run thermoform
        working-directory: ./examples/05_obstacle_type_qvi
        run: julia thermoforming_lvpp.jl
